import type { PiAgentKind } from '../../shared/pi-agent-kind'
import { getPiOmpRuntimeDetectionSourceLines } from './agent-status-runtime-detection-source'

export const ORCA_PI_EXTENSION_FILE = 'orca-titlebar-spinner.ts'

export function getPiTitlebarExtensionSource(kind: PiAgentKind = 'pi'): string {
  // Why: OMP reports input waits through its own approval events, which the status
  // extension already maps, and it writes this same marker natively. The runtime check
  // matters as well as the kind: a bare-shell OMP launch runs inside a pi-kind pane.
  const uiPromptHandlers =
    kind === 'pi'
      ? [
          '  // Why: this source is generated and untypechecked, and pi does not document the',
          '  // ctx it passes these two events, so never let a missing ui fail the handler.',
          "  pi.on('ui_prompt_start', async (_event, ctx) => {",
          '    if (isOmpRuntime()) return',
          '    promptDepth++',
          '    // Why: retry on every open rather than only the outermost, so an outer ctx',
          '    // without ui cannot decide the whole stack stays unmarked.',
          "    if (markerPainted || typeof ctx?.ui?.setTitle !== 'function') return",
          '    // Why: only hold the spinner off once the marker is actually up, or a ctx',
          '    // without ui would freeze the title on its last working frame instead.',
          '    markerPainted = true',
          '    promptCtx = ctx',
          "    ctx.ui.setTitle(getMarkedTitle(pi, '!'))",
          '  })',
          '',
          "  pi.on('ui_prompt_end', async (_event, ctx) => {",
          '    if (isOmpRuntime() || promptDepth === 0) return',
          '    promptDepth--',
          '    if (promptDepth > 0) return',
          '    // Why: the opening ctx is known to paint, so a close that carries no ui does',
          '    // not leave the needs-input marker up until the next turn.',
          '    const painter = ctx?.ui?.setTitle ? ctx : promptCtx',
          '    markerPainted = false',
          '    promptCtx = null',
          '    // Why: a still-live turn resumes its spinner in place; otherwise the pane is idle',
          '    // and must drop the needs-input marker rather than keep asking for attention.',
          '    if (timer && painter?.ui?.setTitle) {',
          '      renderFrame(painter)',
          '      return',
          '    }',
          '    painter?.ui?.setTitle?.(getBaseTitle(pi))',
          '  })',
          ''
        ]
      : []

  return [
    ...(kind === 'pi' ? [...getPiOmpRuntimeDetectionSourceLines(`/hook/${kind}`), ''] : []),
    'const BRAILLE_FRAMES = [',
    "  '\\u280b',",
    "  '\\u2819',",
    "  '\\u2839',",
    "  '\\u2838',",
    "  '\\u283c',",
    "  '\\u2834',",
    "  '\\u2826',",
    "  '\\u2827',",
    "  '\\u2807',",
    "  '\\u280f'",
    ']',
    '',
    'const FRAME_INTERVAL_MS = 80',
    'const AGENT_END_IDLE_RECHECK_MS = 25',
    'const AGENT_END_IDLE_RECHECK_MAX_MS = 250',
    '// Why: a failed idle compaction can end without auto_compaction_end, and no agent turn will',
    '// close a maintenance spinner — cap it so idle maintenance cannot strand a working title.',
    'const IDLE_COMPACTION_MAX_FRAMES = Math.ceil(300000 / FRAME_INTERVAL_MS)',
    '',
    '// Why: `-` is the plain separator; `!` is the state marker Orca reads as needs-input',
    '// (src/shared/pi-state-title-marker.ts), so mobile and the CLI see the wait too.',
    'function getMarkedTitle(pi, marker) {',
    '  const cwd = process.cwd().split(/[\\\\/]/).filter(Boolean).at(-1) || process.cwd()',
    '  const session = pi.getSessionName()',
    '  return session',
    '    ? `\\u03c0 ${marker} ${session} - ${cwd}`',
    '    : `\\u03c0 ${marker} ${cwd}`',
    '}',
    '',
    'function getBaseTitle(pi) {',
    "  return getMarkedTitle(pi, '-')",
    '}',
    '',
    'export default function (pi) {',
    '  if (!process.env.ORCA_PANE_KEY) return',
    '  let timer = null',
    '  let frameIndex = 0',
    '  // Why: only idle maintenance owns a spinner of its own. A threshold compaction runs',
    '  // inside an agent turn, whose spinner must outlive it, and any newer start clears the',
    '  // marker so a late idle completion cannot stop current work (#16470).',
    '  let idleCompactionOwnsSpinner = false',
    '  // Why: count depth rather than trust an undocumented one-pair-per-stack guarantee,',
    '  // so an inner close cannot release the wait the outer dialog still holds. A new turn',
    '  // cannot start under a dialog holding input focus, so agent_start doubles as recovery.',
    '  let promptDepth = 0',
    '  let markerPainted = false',
    '  let promptCtx = null',
    '  let pendingAgentEndCheck = null',
    '  let pendingAgentEndContext = null',
    '  let agentEndIdleRecheckMs = AGENT_END_IDLE_RECHECK_MS',
    '',
    '  function clearPendingAgentEndCheck() {',
    '    if (pendingAgentEndCheck !== null) clearTimeout(pendingAgentEndCheck)',
    '    pendingAgentEndCheck = null',
    '    pendingAgentEndContext = null',
    '  }',
    '',
    '  function clearAnimation() {',
    '    if (timer) {',
    '      clearInterval(timer)',
    '      timer = null',
    '    }',
    '    frameIndex = 0',
    '    idleCompactionOwnsSpinner = false',
    '  }',
    '',
    '  function stopAnimation(ctx) {',
    '    clearPendingAgentEndCheck()',
    '    clearAnimation()',
    '    // Why: settling under an open dialog still leaves the pane waiting on the user, so',
    '    // the idle title must not retire the marker the dialog is holding.',
    "    ctx.ui.setTitle(markerPainted ? getMarkedTitle(pi, '!') : getBaseTitle(pi))",
    '  }',
    '',
    '  function renderFrame(ctx) {',
    '    // Why: the maintenance cap runs before the dialog guard so a dialog left open',
    '    // cannot suspend it; stopAnimation keeps the marker while a dialog is open.',
    '    if (idleCompactionOwnsSpinner && frameIndex >= IDLE_COMPACTION_MAX_FRAMES) {',
    '      stopAnimation(ctx)',
    '      return',
    '    }',
    '    // Why: an 80ms working frame would repaint over the needs-input marker within one',
    '    // tick, so a mid-turn dialog would still look busy everywhere the title is the',
    '    // only evidence. Still count the frame so the cap above keeps accruing in',
    '    // wall-clock; the close resumes the animation in place.',
    '    if (markerPainted) {',
    '      frameIndex++',
    '      return',
    '    }',
    '      const frame = BRAILLE_FRAMES[frameIndex % BRAILLE_FRAMES.length]',
    '      const cwd = process.cwd().split(/[\\\\/]/).filter(Boolean).at(-1) || process.cwd()',
    '      const session = pi.getSessionName()',
    '      const title = session ? `${frame} \\u03c0 - ${session} - ${cwd}` : `${frame} \\u03c0 - ${cwd}`',
    '      ctx.ui.setTitle(title)',
    '      frameIndex++',
    '  }',
    '',
    '  function startAnimation(ctx) {',
    '    clearPendingAgentEndCheck()',
    '    clearAnimation()',
    '    renderFrame(ctx)',
    '    timer = setInterval(() => renderFrame(ctx), FRAME_INTERVAL_MS)',
    '  }',
    '',
    '  function checkPendingAgentEnd() {',
    '    pendingAgentEndCheck = null',
    '    const ctx = pendingAgentEndContext',
    '    if (!ctx) return',
    '    try {',
    '      if (ctx.isIdle()) {',
    '        pendingAgentEndContext = null',
    '        stopAnimation(ctx)',
    '        return',
    '      }',
    '    } catch {',
    '      pendingAgentEndContext = null',
    '      return',
    '    }',
    '    pendingAgentEndCheck = setTimeout(checkPendingAgentEnd, agentEndIdleRecheckMs)',
    "    if (typeof pendingAgentEndCheck.unref === 'function') pendingAgentEndCheck.unref()",
    '    agentEndIdleRecheckMs = Math.min(agentEndIdleRecheckMs * 2, AGENT_END_IDLE_RECHECK_MAX_MS)',
    '  }',
    '',
    "  pi.on('agent_start', async (_event, ctx) => {",
    '    promptDepth = 0',
    '    markerPainted = false',
    '    promptCtx = null',
    '    startAnimation(ctx)',
    '  })',
    '',
    '  // Why: modern Pi/OMP emit agent_end mid-run and only settle later, so settlement is the',
    '  // authoritative completion boundary. Legacy runtimes never emit it, so agent_end stays.',
    "  pi.on('agent_settled', async (_event, ctx) => {",
    '    stopAnimation(ctx)',
    '  })',
    '',
    "  pi.on('agent_end', async (event, ctx) => {",
    '    if (event?.willContinue === true) {',
    '      clearPendingAgentEndCheck()',
    '      return',
    '    }',
    "    if (!ctx || typeof ctx.isIdle !== 'function') {",
    '      stopAnimation(ctx)',
    '      return',
    '    }',
    '    clearPendingAgentEndCheck()',
    '    agentEndIdleRecheckMs = AGENT_END_IDLE_RECHECK_MS',
    '    pendingAgentEndContext = ctx',
    '    pendingAgentEndCheck = setTimeout(checkPendingAgentEnd, 0)',
    "    if (typeof pendingAgentEndCheck.unref === 'function') pendingAgentEndCheck.unref()",
    '  })',
    '',
    ...uiPromptHandlers,
    "  pi.on('auto_compaction_start', async (event, ctx) => {",
    "    if (event?.reason !== 'idle') return",
    '    // Why: the idle worker can fire against a turn that just started, and reason alone does',
    '    // not prove the pane is idle. Adopting a live agent spinner would let the matching',
    '    // auto_compaction_end mark the pane idle mid-run — the inverse of #16470.',
    '    if (timer && !idleCompactionOwnsSpinner) return',
    '    startAnimation(ctx)',
    '    idleCompactionOwnsSpinner = true',
    '  })',
    '',
    "  pi.on('auto_compaction_end', async (_event, ctx) => {",
    '    if (!idleCompactionOwnsSpinner) return',
    '    stopAnimation(ctx)',
    '  })',
    '',
    "  pi.on('session_shutdown', async (_event, ctx) => {",
    '    promptDepth = 0',
    '    markerPainted = false',
    '    promptCtx = null',
    '    stopAnimation(ctx)',
    '  })',
    '}',
    ''
  ].join('\n')
}
